package career
import("context";"encoding/json";"fmt";"github.com/jeevanragula/career-os/internal/ai")
type Agent struct{Name string `json:"name"`;Purpose string `json:"purpose"`;Instruction string `json:"instruction"`;Area string `json:"area"`}
var Registry=[]Agent{
{"career-intelligence","Maintain the career brain.","Identify material changes, contradictions, missing evidence and useful next actions. Never invent facts.","career"},
{"opportunity","Find and act on relevant opportunities.","Review jobs and target roles. Propose opportunity-search improvements and actions. Do not submit applications.","jobs"},
{"skill-gap","Identify skills that strengthen target paths.","Compare skill levels, evidence and targets. Identify gaps and measurable ways to close them. Do not downgrade verified skills.","learning"},
{"learning","Build a focused learning roadmap.","Propose practical learning items tied to target paths; prefer projects and labs over generic courses.","learning"},
{"project","Propose portfolio projects.","Suggest realistic projects that close high-value skill gaps and produce demonstrable evidence.","projects"},
{"resume","Improve resume strategy.","Review career evidence and opportunity patterns. Propose resume strategy changes; actual generation remains evidence-grounded.","resume"},
{"interview","Prepare for senior interviews.","Create targeted architecture, distributed systems, cloud/security, AI systems, leadership and behavioral preparation themes.","interview"},
{"networking","Develop deliberate relationships.","Suggest follow-ups, people to research and value-first outreach topics. Do not send messages.","network"},
{"personal-brand","Strengthen public presence.","Suggest evidence-backed LinkedIn, GitHub, article and talk topics. Do not publish automatically.","brand"},
{"startup","Evaluate startup ideas as experiments.","Suggest customer/problem validation experiments, not speculative certainty.","startup"},
{"market-intelligence","Track relevant technology and hiring changes.","Identify external market information to research next and how it could affect skills or positioning. Do not predict outcomes.","market"},
{"achievement","Capture reusable career evidence.","Identify achievements worth capturing and evidence artifacts. Never fabricate metrics or confidential details.","evidence"},
{"portfolio","Prepare safe public portfolio updates.","Identify public-safe evidence that could improve the portfolio. Do not publish private information.","portfolio"},
{"career-strategy","Run a neutral career review.","Synthesize goals, skills, opportunities, learning, network, startups and outcomes into strategic options and actions. Do not choose a path for the user.","strategy"},
}
func RunAgent(ctx context.Context,st *Store,client ai.Client,name,trigger string)(map[string]any,error){var spec *Agent;for i:=range Registry{if Registry[i].Name==name{spec=&Registry[i];break}};if spec==nil{return nil,fmt.Errorf("unknown agent %q",name)};ctxData,e:=st.AgentContext(ctx);if e!=nil{return nil,e};if client.BaseURL==""||client.Model==""{return map[string]any{"agent":name,"status":"needs_ai_configuration","message":"Configure AI_BASE_URL and AI_MODEL to run this agent.","actions":[]any{}},nil};raw,e:=client.Complete(ctx,"You are the "+spec.Name+" agent in CareerOS. "+spec.Instruction+" Return ONLY JSON with keys summary, recommendations (array of title,rationale,action,priority), tasks (array of title,area,priority,notes), followups (array of strings).",fmt.Sprintf("CareerOS context:\n%s",mustJSON(ctxData)));if e!=nil{return nil,e};var out map[string]any;if e=json.Unmarshal([]byte(raw),&out);e!=nil{return nil,fmt.Errorf("agent returned invalid JSON: %w",e)};if recs,ok:=out["recommendations"].([]any);ok{for _,v:=range recs{m,_:=v.(map[string]any);title,_:=m["title"].(string);rat,_:=m["rationale"].(string);act,_:=m["action"].(string);p:=3;if n,ok:=m["priority"].(float64);ok{p=int(n)};if title!=""{if e:=st.InsertRecommendation(ctx,name,title,rat,act,p,m);e!=nil{return nil,e}}}};if tasks,ok:=out["tasks"].([]any);ok{for _,v:=range tasks{m,_:=v.(map[string]any);title,_:=m["title"].(string);area,_:=m["area"].(string);notes,_:=m["notes"].(string);p:=3;if n,ok:=m["priority"].(float64);ok{p=int(n)};if title!=""{if _,e:=st.CreateTask(ctx,title,area,name,p,notes);e!=nil{return nil,e}}}};return out,nil}
func mustJSON(v any)string{b,_:=json.MarshalIndent(v,"","  ");return string(b)}
