package career
import "time"
type Dashboard struct { Goals []Goal `json:"goals"`; Skills []Skill `json:"skills"`; Learning []LearningItem `json:"learning"`; Tasks []Task `json:"tasks"`; Recommendations []Recommendation `json:"recommendations"`; Opportunities []OpportunitySummary `json:"opportunities"`; Network []Contact `json:"network"`; Startups []StartupIdea `json:"startups"`; AgentRuns []AgentRun `json:"agent_runs"`; Stats Stats `json:"stats"` }
type Goal struct { ID string `json:"id"`; Title string `json:"title"`; Description string `json:"description"`; Status string `json:"status"`; Priority int `json:"priority"`; TargetDate *time.Time `json:"target_date,omitempty"` }
type Skill struct { ID string `json:"id"`; Name string `json:"name"`; Category string `json:"category"`; Level int `json:"level"`; TargetLevel *int `json:"target_level,omitempty"`; EvidenceSummary string `json:"evidence_summary"` }
type LearningItem struct { ID string `json:"id"`; Title string `json:"title"`; Skill string `json:"skill"`; Type string `json:"type"`; Status string `json:"status"`; URL string `json:"url"`; Notes string `json:"notes"`; DueDate *time.Time `json:"due_date,omitempty"` }
type Contact struct { ID string `json:"id"`; Name string `json:"name"`; Company string `json:"company"`; Role string `json:"role"`; ProfileURL string `json:"profile_url"`; Relationship string `json:"relationship"`; FollowUpAt *time.Time `json:"follow_up_at,omitempty"`; Notes string `json:"notes"` }
type StartupIdea struct { ID string `json:"id"`; Name string `json:"name"`; Problem string `json:"problem"`; Customer string `json:"customer"`; Hypothesis string `json:"hypothesis"`; Status string `json:"status"`; Notes string `json:"notes"` }
type Task struct { ID string `json:"id"`; Title string `json:"title"`; Area string `json:"area"`; Status string `json:"status"`; Priority int `json:"priority"`; DueAt *time.Time `json:"due_at,omitempty"`; SourceAgent string `json:"source_agent"`; Notes string `json:"notes"` }
type Recommendation struct { ID string `json:"id"`; AgentName string `json:"agent_name"`; Title string `json:"title"`; Rationale string `json:"rationale"`; Action string `json:"action"`; Priority int `json:"priority"`; Status string `json:"status"`; Payload map[string]any `json:"payload"` }
type OpportunitySummary struct { ID string `json:"id"`; Company string `json:"company"`; Title string `json:"title"`; Location string `json:"location"`; URL string `json:"url"`; Status string `json:"status"` }
type AgentRun struct { ID string `json:"id"`; AgentName string `json:"agent_name"`; Trigger string `json:"trigger"`; Status string `json:"status"`; Model string `json:"model"`; StartedAt time.Time `json:"started_at"`; CompletedAt *time.Time `json:"completed_at,omitempty"` }
type Stats struct { Jobs int `json:"jobs"`; OpenTasks int `json:"open_tasks"`; Recommendations int `json:"recommendations"`; LearningInProgress int `json:"learning_in_progress"`; FollowUps int `json:"follow_ups"`; Startups int `json:"startups"` }