package career
import ("context";"database/sql";"encoding/json")
type Store struct{DB *sql.DB}
func(s Store)Dashboard(ctx context.Context)(Dashboard,error){var d Dashboard;var e error;if d.Goals,e=s.goals(ctx);e!=nil{return d,e};if d.Skills,e=s.skills(ctx);e!=nil{return d,e};if d.Learning,e=s.learning(ctx);e!=nil{return d,e};if d.Tasks,e=s.tasks(ctx);e!=nil{return d,e};if d.Recommendations,e=s.recommendations(ctx);e!=nil{return d,e};if d.Network,e=s.network(ctx);e!=nil{return d,e};if d.Startups,e=s.startups(ctx);e!=nil{return d,e};if d.AgentRuns,e=s.agentRuns(ctx);e!=nil{return d,e};d.Stats,e=s.stats(ctx);if e!=nil{return d,e};d.Opportunities,e=s.opportunities(ctx);return d,e}
func(s Store)goals(c context.Context)([]Goal,error){r,e:=s.DB.QueryContext(c,"SELECT id,title,description,status,priority,target_date FROM career_goals WHERE status='active' ORDER BY priority,title");if e!=nil{return nil,e};defer r.Close();var o []Goal;for r.Next(){var x Goal;if e=r.Scan(&x.ID,&x.Title,&x.Description,&x.Status,&x.Priority,&x.TargetDate);e!=nil{return nil,e};o=append(o,x)};return o,r.Err()}
func(s Store)skills(c context.Context)([]Skill,error){r,e:=s.DB.QueryContext(c,"SELECT id,name,category,level,target_level,evidence_summary FROM skills ORDER BY category,name");if e!=nil{return nil,e};defer r.Close();var o []Skill;for r.Next(){var x Skill;if e=r.Scan(&x.ID,&x.Name,&x.Category,&x.Level,&x.TargetLevel,&x.EvidenceSummary);e!=nil{return nil,e};o=append(o,x)};return o,r.Err()}
func(s Store)learning(c context.Context)([]LearningItem,error){r,e:=s.DB.QueryContext(c,"SELECT id,title,skill,type,status,url,notes,due_date FROM learning_items WHERE status<>'dropped' ORDER BY status,due_date NULLS LAST,created_at DESC LIMIT 20");if e!=nil{return nil,e};defer r.Close();var o []LearningItem;for r.Next(){var x LearningItem;if e=r.Scan(&x.ID,&x.Title,&x.Skill,&x.Type,&x.Status,&x.URL,&x.Notes,&x.DueDate);e!=nil{return nil,e};o=append(o,x)};return o,r.Err()}
func(s Store)tasks(c context.Context)([]Task,error){r,e:=s.DB.QueryContext(c,"SELECT id,title,area,status,priority,due_at,source_agent,notes FROM career_tasks WHERE status IN ('todo','in_progress') ORDER BY priority,due_at NULLS LAST LIMIT 30");if e!=nil{return nil,e};defer r.Close();var o []Task;for r.Next(){var x Task;if e=r.Scan(&x.ID,&x.Title,&x.Area,&x.Status,&x.Priority,&x.DueAt,&x.SourceAgent,&x.Notes);e!=nil{return nil,e};o=append(o,x)};return o,r.Err()}
func(s Store)recommendations(c context.Context)([]Recommendation,error){r,e:=s.DB.QueryContext(c,"SELECT id,agent_name,title,rationale,action,priority,status,payload FROM career_recommendations WHERE status='proposed' ORDER BY priority,created_at DESC LIMIT 20");if e!=nil{return nil,e};defer r.Close();var o []Recommendation;for r.Next(){var x Recommendation;var raw []byte;if e=r.Scan(&x.ID,&x.AgentName,&x.Title,&x.Rationale,&x.Action,&x.Priority,&x.Status,&raw);e!=nil{return nil,e};_ = json.Unmarshal(raw,&x.Payload);o=append(o,x)};return o,r.Err()}
func(s Store)network(c context.Context)([]Contact,error){r,e:=s.DB.QueryContext(c,"SELECT id,name,company,role,profile_url,relationship,follow_up_at,notes FROM network_contacts ORDER BY follow_up_at NULLS LAST,created_at DESC LIMIT 20");if e!=nil{return nil,e};defer r.Close();var o []Contact;for r.Next(){var x Contact;if e=r.Scan(&x.ID,&x.Name,&x.Company,&x.Role,&x.ProfileURL,&x.Relationship,&x.FollowUpAt,&x.Notes);e!=nil{return nil,e};o=append(o,x)};return o,r.Err()}
func(s Store)startups(c context.Context)([]StartupIdea,error){r,e:=s.DB.QueryContext(c,"SELECT id,name,problem,customer,hypothesis,status,notes FROM startup_ideas ORDER BY updated_at DESC LIMIT 12");if e!=nil{return nil,e};defer r.Close();var o []StartupIdea;for r.Next(){var x StartupIdea;if e=r.Scan(&x.ID,&x.Name,&x.Problem,&x.Customer,&x.Hypothesis,&x.Status,&x.Notes);e!=nil{return nil,e};o=append(o,x)};return o,r.Err()}
func(s Store)agentRuns(c context.Context)([]AgentRun,error){r,e:=s.DB.QueryContext(c,"SELECT id,agent_name,trigger,status,model,started_at,completed_at FROM agent_runs ORDER BY started_at DESC LIMIT 10");if e!=nil{return nil,e};defer r.Close();var o []AgentRun;for r.Next(){var x AgentRun;if e=r.Scan(&x.ID,&x.AgentName,&x.Trigger,&x.Status,&x.Model,&x.StartedAt,&x.CompletedAt);e!=nil{return nil,e};o=append(o,x)};return o,r.Err()}
func(s Store)opportunities(c context.Context)([]OpportunitySummary,error){r,e:=s.DB.QueryContext(c,"SELECT j.id,j.company,j.title,COALESCE(j.location,''),COALESCE(j.canonical_url,''),j.status,COALESCE(m.score,0),COALESCE(m.matched_skills,'[]'::jsonb),COALESCE(m.gaps,'[]'::jsonb),COALESCE(m.rationale,'') FROM jobs j LEFT JOIN opportunity_matches m ON m.job_id=j.id WHERE j.status IN ('open','unknown') ORDER BY COALESCE(m.score,0) DESC,j.last_seen_at DESC LIMIT 20");if e!=nil{return nil,e};defer r.Close();var o []OpportunitySummary;for r.Next(){var x OpportunitySummary;var ms,gs []byte;if e=r.Scan(&x.ID,&x.Company,&x.Title,&x.Location,&x.URL,&x.Status,&x.Score,&ms,&gs,&x.Rationale);e!=nil{return nil,e};_ = json.Unmarshal(ms,&x.MatchedSkills);_ = json.Unmarshal(gs,&x.Gaps);o=append(o,x)};return o,r.Err()}
func(s Store)stats(c context.Context)(Stats,error){var x Stats;e:=s.DB.QueryRowContext(c,"SELECT (SELECT count(*) FROM jobs),(SELECT count(*) FROM career_tasks WHERE status IN ('todo','in_progress')),(SELECT count(*) FROM career_recommendations WHERE status='proposed'),(SELECT count(*) FROM learning_items WHERE status='in_progress'),(SELECT count(*) FROM network_contacts WHERE follow_up_at IS NOT NULL AND follow_up_at<=now()),(SELECT count(*) FROM startup_ideas WHERE status NOT IN ('closed','paused'))").Scan(&x.Jobs,&x.OpenTasks,&x.Recommendations,&x.LearningInProgress,&x.FollowUps,&x.Startups);return x,e}
func(s Store)CompleteRecommendation(c context.Context,id,status string)error{_,e:=s.DB.ExecContext(c,"UPDATE career_recommendations SET status=$2,updated_at=now() WHERE id=$1",id,status);return e}
func(s Store)CompleteTask(c context.Context,id string)error{_,e:=s.DB.ExecContext(c,"UPDATE career_tasks SET status='done',updated_at=now() WHERE id=$1",id);return e}
func(s Store)CreateTask(c context.Context,title,area,agent string,p int,notes string)(string,error){var id string;e:=s.DB.QueryRowContext(c,"INSERT INTO career_tasks(title,area,source_agent,priority,notes) VALUES($1,$2,$3,$4,$5) RETURNING id",title,area,agent,p,notes).Scan(&id);return id,e}
func(s Store)InsertRecommendation(c context.Context,agent,title,rationale,action string,p int,payload map[string]any)error{raw,_:=json.Marshal(payload);_,e:=s.DB.ExecContext(c,"INSERT INTO career_recommendations(agent_name,title,rationale,action,priority,payload) VALUES($1,$2,$3,$4,$5,$6)",agent,title,rationale,action,p,raw);return e}
func(s Store)AgentContext(c context.Context)(map[string]any,error){d,e:=s.Dashboard(c);if e!=nil{return nil,e};return map[string]any{"goals":d.Goals,"skills":d.Skills,"learning":d.Learning,"tasks":d.Tasks,"recommendations":d.Recommendations,"opportunities":d.Opportunities,"network":d.Network,"startups":d.Startups},nil}
