let state={};const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function toast(m,good=false){const e=$('toast');e.textContent=m;e.className='toast '+(good?'good':'error');e.style.display='block';setTimeout(()=>e.style.display='none',4000)}
async function api(url,opt={}){opt.credentials='same-origin';const r=await fetch(url,opt);const t=await r.text();let d={};try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d.error||('Request failed ('+r.status+')'));return d}
async function load(){try{state=await api('/api/dashboard');render();await Promise.all([loadAgents(),loadCandidates(),loadStatus()])}catch(e){toast(e.message)}}
function render(){const s=state.stats||{};$('stats').innerHTML=[['opportunities',s.jobs||0],['open actions',s.open_tasks||0],['recommendations',s.recommendations||0],['learning',s.learning_in_progress||0]].map(x=>'<div class="stat"><b>'+esc(x[1])+'</b><span>'+esc(x[0])+'</span></div>').join('');
$('jobs').innerHTML=(state.opportunities||[]).map(j=>'<article class="job"><div class="job-main"><div class="job-title">'+esc(j.title)+'</div><div class="meta">'+esc(j.company)+' · '+esc(j.location||'Location not specified')+'</div><p>'+esc(j.rationale||'No explanation yet.')+'</p>'+(j.matched_skills?.length?'<div class="chips">'+j.matched_skills.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div>':'')+(j.gaps?.length?'<div class="meta gap">Gaps: '+esc(j.gaps.join(', '))+'</div>':'')}</div><div class="job-actions"><strong>'+Number(j.score||0).toFixed(0)+'/100</strong>'+(j.url?'<a class="btn secondary small" target="_blank" rel="noopener" href="'+esc(j.url)+'">Open role</a>':'')+'<button class="btn small" onclick="analyze(\''+j.id+'\')">Analyze</button><button class="btn secondary small" onclick="resume(\''+j.id+'\')">Resume</button></div></article>').join('')||'<div class="empty big">No opportunities yet.<br><span>Run discovery above to build your inbox.</span></div>';
$('tasks').innerHTML=(state.tasks||[]).slice(0,5).map(x=>'<div class="item"><strong>'+esc(x.title)+'</strong><div class="meta">'+esc(x.area)+' · priority '+x.priority+'</div><button class="btn secondary small" onclick="doneTask(\''+x.id+'\')">Done</button></div>').join('')||'<div class="empty">No open actions.</div>';
$('recs').innerHTML=(state.recommendations||[]).slice(0,4).map(x=>'<div class="item"><strong>'+esc(x.title)+'</strong><div class="meta">'+esc(x.agent_name)+'</div><p>'+esc(x.rationale)+'</p><div class="actions"><button class="btn small" onclick="rec(\''+x.id+'\',\'accepted\')">Accept</button><button class="btn secondary small" onclick="rec(\''+x.id+'\',\'dismissed\')">Dismiss</button></div></div>').join('')||'<div class="empty">Run an AI agent when AI is configured.</div>';
$('goals').innerHTML=(state.goals||[]).map(g=>'<div class="item"><strong>'+esc(g.title)+'</strong><div class="meta">'+esc(g.description)+'</div></div>').join('')||'<div class="empty">No active goals.</div>';
$('learning').innerHTML=(state.learning||[]).map(x=>'<div class="item"><strong>'+esc(x.title)+'</strong><div class="meta">'+esc(x.skill)+' · '+esc(x.status)+'</div></div>').join('')||'<div class="empty">No learning items.</div>';
$('network').innerHTML=(state.network||[]).map(x=>'<div class="item"><strong>'+esc(x.name)+'</strong><div class="meta">'+esc(x.role)+' · '+esc(x.company)+'</div></div>').join('')||'<div class="empty">No contacts yet.</div>';
$('startups').innerHTML=(state.startups||[]).map(x=>'<div class="item"><strong>'+esc(x.name)+'</strong><div class="meta">'+esc(x.status)+'</div></div>').join('')||'<div class="empty">No startup tracks.</div>';
$('skills').innerHTML=(state.skills||[]).map(x=>'<div class="skill"><strong>'+esc(x.name)+'</strong><span>'+x.level+'/5</span></div>').join('')}
async function loadStatus(){const s=await api('/api/status');const rows=[['Database',s.database,'Core data store'],['Tavily discovery',s.tavily,'Required for web opportunity search'],['AI agents',s.ai,'Required for Analyze, Resume and agent runs']];$('status').innerHTML=rows.map(x=>'<div class="status-row"><div><strong>'+esc(x[0])+'</strong><div class="meta">'+esc(x[2])+'</div></div><span class="status-pill '+(x[1]?'ok':'warn')+'">'+(x[1]?'Ready':'Not configured')+'</span></div>').join('');$('heroTitle').textContent=s.tavily?'Your opportunity radar is ready':'Connect Tavily to start discovering opportunities';$('heroText').textContent=s.tavily?'Search for roles and CareerOS will build your opportunity inbox.':'Add TAVILY_API_KEY to your .env, restart CareerOS, then run discovery.'}
async function loadAgents(){try{const d=await api('/api/agents');$('agents').innerHTML=d.agents.map(a=>'<div class="agent"><strong>'+esc(a.name)+'</strong><div class="meta">'+esc(a.purpose)+'</div><button class="btn small" onclick="runAgent(\''+a.name+'\')">Run</button></div>').join('')}catch(e){$('agents').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function loadCandidates(){try{const d=await api('/api/discovery/candidates');$('candidates').innerHTML=(d.candidates||[]).map(x=>'<div class="item"><strong>'+esc(x.name)+'</strong><div class="meta">'+esc(x.evidence)+'</div></div>').join('')||'<div class="empty">No discovered companies yet.</div>'}catch(e){$('candidates').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function runDiscovery(){const b={roles:$('roles').value.split(',').map(x=>x.trim()).filter(Boolean),locations:$('locations').value.split(',').map(x=>x.trim()).filter(Boolean)};const btns=[$('discover'),$('discoverHero'),$('discoverBottom')];btns.forEach(b=>{if(b)b.disabled=true});$('discoveryStatus').textContent='Searching Tavily, resolving career pages and matching roles…';try{const d=await api('/api/discover/automatic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});$('discoveryStatus').textContent='Completed: '+d.candidates+' signals · '+d.career_pages+' career pages · '+d.jobs_ingested+' jobs · '+d.opportunities_matched+' matches.';toast('Discovery completed',true);await load()}catch(e){$('discoveryStatus').textContent='Discovery failed: '+e.message;toast(e.message)}finally{btns.forEach(b=>{if(b)b.disabled=false})}}
async function runAgent(name){toast('Running '+name+'…');try{await api('/api/agents/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});toast(name+' completed',true);await load()}catch(e){toast(e.message)}}
async function doneTask(id){try{await api('/api/tasks/'+id,{method:'POST'});await load()}catch(e){toast(e.message)}}
async function rec(id,status){try{await api('/api/recommendations/'+id+'?status='+status,{method:'POST'});await load()}catch(e){toast(e.message)}}
async function analyze(id){try{await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:id})});toast('Job analyzed',true);await load()}catch(e){toast(e.message)}}
async function resume(id){try{const d=await api('/api/resume',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:id})});const w=window.open();w.document.write('<pre style="white-space:pre-wrap;font:14px system-ui;padding:24px">'+esc(d.content)+'</pre>');w.document.close()}catch(e){toast(e.message)}}
$('refresh').onclick=load;$('discover').onclick=runDiscovery;$('discoverHero').onclick=runDiscovery;$('discoverBottom').onclick=runDiscovery;load();